defaults: &defaults
  toggle_signup_status: "closed"
  toggle_admin_view: "enabled"
  toggle_deficient_trainings_view: "enabled"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
